### ISSUE TITLE
pepper destroy abort fails

### ISSUE THREAD

**Issue by tsmilam** [nextgearcapital/pepper#6]
When pepper destroy prompt Y/n to confirm that you want to destroy a server, selecting 'n' to abort does not work. Here's some sample output:
`
pepper destroy exp1ddevsm01
`
Are you sure you want to destroy [exp1ddevsm01]? [Y/n] n
`
Aborted!
`
---> Executing: salt-cloud -y -d exp1ddevsm01
`
[INFO    ] salt-cloud starting
`

**Comment by rdeusser** [comment]
Ah yes. Silly me. I'll open a PR to fix that.
